#!/bin/bash

#USE scdinstall.sh IF YOU DON'T WANT TO CONFIGURE MANUALLY, TESTED ON DEBIAN BUSTER

#SCD = Super Change Directory, cd and list current folder
#Add file to ~/bin/
#Add export PATH=$PATH:~/bin and alias scd =". ~/bin/sdc"
#Remember to chmod 755, run as: scd folder_name


cd $1
pwd
ls --color=auto -larth .
