#!/bin/bash
#Short example server for sleepwalking startup script
case "$1" in
	start)
		/tmp/sleepwalkingserver &
		;;
	stop)
		kill $(cat /tmp/sleepwalkingserver.pid)
		;;
	*)
		echo "Usage sleepwalking start|stop"
		exit 1
esac
